# Generated by Django 3.1.6 on 2021-02-06 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManageReview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_sections', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('type', models.CharField(choices=[('anonymous', 'anonymous'), ('Fresh Food', 'Fresh Food'), ('Food Cupboard', 'Food Cupboard'), ('Frozen Food', 'Frozen Food'), ('Beverages', 'Beverages'), ('Bio & Organic Food', 'Bio & Organic Food'), ('Baby Product', 'Baby Product'), ('Cleaning & Household', 'Cleaning & Household'), ('Health & Fitness', 'Health & Fitness'), ('Smartphones, Tablets & Wearables', 'Smartphones, Tablets & Wearables'), ('Electronics & Appliances', 'Electronics & Appliances'), ('Home & Garden', 'Home & Garden'), ('Pet Supplies ', 'Pet Supplies '), ('Toys & OutDoor', 'Toys & OutDoor'), ('Stationery & School Supplies', 'Stationery & School Supplies'), ('Kiosk', 'Kiosk'), ('Automotive', 'Automotive')], max_length=50)),
                ('number_Of_Copy', models.PositiveIntegerField(blank=True, null=True)),
                ('par_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('manufacturer', models.CharField(choices=[('Manufacturer 1', 'Manufacturer 1'), ('Manufacturer 2', 'Manufacturer 2')], default='anonymous Manufacturer', max_length=50)),
                ('image', models.ImageField(default='Product default.png', upload_to='Products')),
                ('discount', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ProductReview', models.ManyToManyField(blank=True, to='ManageReview.Review')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
