# Generated by Django 3.1.6 on 2021-02-06 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManageOffer', '0001_initial'),
        ('ManageProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageProduct.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('Offer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManageOffer.offer')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_finished_adding', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(blank=True, to='ShoppingCart.CartItem')),
                ('offers', models.ManyToManyField(blank=True, to='ShoppingCart.CartOffer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
