# Generated by Django 3.1.6 on 2021-02-06 22:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManageReview', '0001_initial'),
        ('ManageProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiratiDate', models.DateTimeField(default=datetime.datetime.now)),
                ('state', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('number_OF_Copy', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('image', models.ImageField(default='package default.jpg', upload_to='Offers')),
                ('slug', models.SlugField(unique=True)),
                ('products', models.ManyToManyField(blank=True, to='ManageProduct.Product')),
                ('review', models.ManyToManyField(blank=True, to='ManageReview.Review')),
            ],
        ),
    ]
